app.Infos.apropos:
    path: /Homepage/Infos/apropos
    controller: App\Controller\Infos\InfosController::infosAPropos
        
app.Infos.conditions:
    path: /Homepage/Infos/conditions
    controller: App\Controller\Infos\InfosController::conditions